name       : mate-screensaver
version    : 1.20.3
release    : 12
source     :
    - https://github.com/mate-desktop/mate-screensaver/archive/v1.20.3.tar.gz : 74c44b6179fe621016074ad0d085407042626d900d35a4dd9dfb96f0fbf2db01
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.mate
summary    : MATE Screensaver and Locker
description: |
    MATE Screensaver and Locker
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libnotify)
    - pkgconfig(libsystemd)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
    - mate-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.

    rm -rf $installdir/etc
    install -Dm00644 $pkgfiles/mate-screensaver $installdir/usr/share/defaults/etc/pam.d/mate-screensaver
