name       : mate-screensaver
version    : 1.18.0
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-screensaver-1.18.0.tar.xz : d5b5bbadb3ac4917b920f500f0d19f803565b2f209652851c2e7a615ecb7c0d5
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.mate
summary    : MATE Screensaver and Locker
description: |
    MATE Screensaver and Locker
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libnotify)
    - pkgconfig(libsystemd)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
