name       : mate-screensaver
version    : 1.24.1
release    : 18
source     :
    - https://github.com/mate-desktop/mate-screensaver/releases/download/v1.24.1/mate-screensaver-1.24.1.tar.xz : bc0925002fccb2de3b36cc37b16ad2becf994c61260dfc5b4930fcedc50fab46
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.mate
summary    : MATE Screensaver and Locker
description: |
    MATE Screensaver and Locker
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libnotify)
    - pkgconfig(libsystemd)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xxf86vm)
setup      : |
    %configure --with-mit-ext --without-console-kit
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.

    rm -rf $installdir/etc
    install -Dm00644 $pkgfiles/mate-screensaver $installdir/usr/share/defaults/etc/pam.d/mate-screensaver
