name       : mate-screensaver
version    : 1.22.1
release    : 14
source     :
    - https://github.com/mate-desktop/mate-screensaver/archive/v1.22.1.tar.gz : 04a3f5acc602224e147613967f43c5e6a5631608b511db13abfb22ec71b73b87
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.mate
summary    : MATE Screensaver and Locker
description: |
    MATE Screensaver and Locker
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libnotify)
    - pkgconfig(libsystemd)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
    - mate-common
setup      : |
    %autogen --with-mit-ext --without-console-kit
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.

    rm -rf $installdir/etc
    install -Dm00644 $pkgfiles/mate-screensaver $installdir/usr/share/defaults/etc/pam.d/mate-screensaver
