name       : mate-screensaver
version    : 1.16.0
release    : 3
source     :
    - http://pub.mate-desktop.org/releases/1.16/mate-screensaver-1.16.0.tar.xz : fda3051346f4d23b383142fe5a86abb7e745c4a3fbcd9ac0c449fbc8a1cb5aa5
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.mate
summary    : MATE Screensaver and Locker
description: |
    MATE Screensaver and Locker
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsystemd)
    - pkgconfig(libmate-menu)
    - pkgconfig(libnotify)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
setup      : |
    %configure --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
