name       : mate-screensaver
version    : 1.20.0
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-screensaver-1.20.0.tar.xz : 69927e32b49b9723ab26a9cc0005f84ff904103d9eb71e926dc44d5311302899
license    :
    - GPL-2.0
    - LGPL-2.0
component  : desktop.mate
summary    : MATE Screensaver and Locker
description: |
    MATE Screensaver and Locker
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libnotify)
    - pkgconfig(libsystemd)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
