name       : mate-screensaver
version    : 1.20.2
release    : 10
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-screensaver-1.20.2.tar.xz : 7d70062e0fd7bbb83bf9b828b9dd5b5e2658b96a97d619cb61ad9ed36c9baee1
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.mate
summary    : MATE Screensaver and Locker
description: |
    MATE Screensaver and Locker
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmate-menu)
    - pkgconfig(libnotify)
    - pkgconfig(libsystemd)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(x11)
    - pkgconfig(xscrnsaver)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    mv $installdir/etc/xdg $installdir/usr/share/.
